### ISSUE TITLE
XNS Purchased have disappeared 

### ISSUE THREAD

**Issue by MetaTireMan** [XYOracleNetwork/os#5]
I had to clear my Chrome browser cookies and now my Chrome XYO o/s node has a new Public Address.  The address where i purchased 4 xNS was replaced with a new public address.  When i imported my Secret SeedPhrase with my node with xNS it is not updating with old public address and xNS are not showing?  

My original node public address was (0x2BF6d0483a289c828427779789A0deFD602Ad6B5...after i cleared my cookies the address changed to (0xc8ddef9c8a7fc01b459a198fe979f60a492204e8)...after i import me seedPhrase from the 0x2BF6 address it does not import my xNS i purchased  nor update the node address?

xNS which I have purchased under 0x2BF6d0483a289c828427779789A0deFD602Ad6B5 were:
- MetaTireMan.XYO
- TownFair.XYO
- MetaTownFair.XYO
- TownFairTire.XYO

![xNS Domains](https://github.com/XYOracleNetwork/os/assets/167895958/940a063e-ff0e-4bab-9384-c0de4f3616e3)

Please let me know if you need any other details...Thank you

**Comment by JoelBCarter** [comment]
@MetaTireMan Thanks for being one of our earliest name owners!  Sorry that happened to you.  We just pushed a build that should allow you to add previously purchased names back in by searching for them in the [My Names tab of the NS Dapp](https://node.xyo.network/name-service/my-names).  Search for your names (might need to be all lowercase and omit the `.xyo` suffix) and if we detect that the wallet searching is the wallet that owns the name, we'll automatically add the name back to your list for you.

We're working on ways to make that experience of clearing your browser less jarring.  For some rational as to why this happened. In something like a web2 model (or even some web3 systems) where all your settings/state are stored a some centralized server somewhere it is pretty easy to keep all that info on you.  With xyOS we are actively trying not to be the maintainer of all that info about you and leaning into a more decentralized/sovereign OS model.  So we keep as much of the OS state as we can in the browser. That has some rough edges in terms of the typical conveniences you expect when [insert Big Corp] keeps all the info about you on their servers.

**Comment by MetaTireMan** [comment]
Appreciate @JoelBCarter for the update!...

Great news!!!

**Comment by MetaTireMan** [comment]
Do I need to reimport my seed phrase from NODE "0x2BF6d0483a289c828427779789A0deFD602Ad6B5" before I do the search?

**Comment by MetaTireMan** [comment]
I did both...reimported seedPhrase & connected wallet associated to the purchase.  Still not showing, however I did notice NODE homescreen is BETA, whereas NameServices screen is still saying ALPHA.  Maybe I need to wait for BETA to be pushed to xNS page?

**Comment by MetaTireMan** [comment]
Please see attached screenshot...i am able to retrieve three of the four xNS.

I was not able to retrieve "MetaTireMan.XYO"

When I had to purchase MetaTireMan it failed on the first transaction...

https://etherscan.io/tx/0x47d78ebdc85d563298f5c8b684047e9f55d643f5c60876857169904b66c23ae6

Transaction was successful, however I never received my xNS.

The next day I repurchased on a different browser.

**WHAT I NOTICED,,,
When I purchased this xNS on the FIRST transaction I was doing it on a browser my current XYO Wallet was not connected to.  The NowPayments popup modal opens up and allows me to connect my XYO wallet, however the was no association to the XYO Wallet and Public NODE.**

**The next day on my second try...I used a browser my XYO WALLET was associated to...There was no issues on this transaction.**

![Missing 1 xNS](https://github.com/XYOracleNetwork/os/assets/167895958/8e7fa32a-3ecd-4647-abe2-b4b4fc526634)

**Comment by jonesmac** [comment]
@MetaTireMan I'm going to close this in light of 4 of the 5 came back and we will track the remaining issue in https://github.com/XYOracleNetwork/os/issues/6
